/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ka.wada' at '17/07/01 12:54' with Gradle 3.1
 *
 * @author ka.wada, @date 17/07/01 12:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
